<!-- The Modal -->
<div id="modalTermsOfUse" class="modal">

    <!-- Modal content -->
    <div class="modal-content-for-data-collection" style="font-family: 'Times New Roman'">
        <span id="spanTermsOfUse" class="close">&times;</span>
        <span style="text-align: center">
        <h1 style='font-size:20px;color:black;margin:0cm;font-family:"Times New Roman",serif;text-align:center;'>ПОЛЬЗОВАТЕЛЬСКОЕ СОГЛАШЕНИЕ</h1>


            <hr class="form-auth__separator">
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><strong><span
                style='font-size:19px;font-family:"Times New Roman",serif;color:black;background:white;'></span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>1. <strong>ТЕРМИНЫ И ОПРЕДЕЛЕНИЯ, ИСПОЛЬЗУЕМЫЕ В НАСТОЯЩЕМ СОГЛАШЕНИИ</strong></span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Перечисленные ниже термины в рамках настоящего Соглашения имеют следующее значение:</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>1.1.&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личный кабинет</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;&ndash; совокупность всей информации</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;для арендатора, содержащий всю информацию в рамках договора аренды,&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>находящаяся в сети интернет по адресу https://skcn.kz/ru/cabinet, принадлежащая</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;Акционерному обществу &laquo;Samruk-Kazyna Construction&raquo; (далее - Общество)</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>1.</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>2</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>. Пользователь&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личного кабинета</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;(далее &ndash; Пользователь) &ndash; лицо, использующее&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>личный кабинет</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>АО &laquo;Samruk-Kazyna Construction&raquo;.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>1.</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>3</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>. Стороны &ndash; АО &laquo;Samruk-Kazyna Construction&raquo; и Пользователь&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>личного кабинета</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>, заключившие Настоящее Соглашение.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>В Условиях могут быть использованы термины, не определенные настоящим документом. В этом случае следует руководствоваться толкованием термина, определенным действующим законодательством Республики Казахстан.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>2. <strong>ОБЩИЕ ПОЛОЖЕНИЯ</strong></span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>2.1. Настоящее Пользовательское соглашение (далее &ndash; Соглашение) относится к&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личному кабинету</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>АО &laquo;Samruk-Kazyna Construction&raquo;, расположенному в сети интернет по адресу https://skcn.kz/ru/cabinet.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>2.2. Сайт является собственностью Акционерно</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>го</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;обществ</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>а</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;&laquo;Samruk-Kazyna Construction&raquo;.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>2.3. Настоящее Соглашение регулирует отношения между АО &laquo;Samruk-Kazyna Construction&raquo; и Пользователь&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личного кабинета</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>2.4. АО &laquo;Samruk-Kazyna Construction&raquo; оставляет за собой право в любое время изменять, добавлять или удалять пункты настоящего Соглашения без уведомления Пользователя.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>2.5. Продолжение использования&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личного кабинета</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;Пользователем означает принятие условий Соглашения и изменений к нему, внесенных в настоящее Соглашение.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>2.6. Пользователь несет персональную ответственность за проверку настоящего Соглашения на наличие изменений в нем.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>2.7. Соглашение вступает в силу с момента выражения Пользователем согласия с его условиями, начиная просмотр&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личного кабинета</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>, либо пройдя процедуру регистрации, Пользователь считается принявшим условия Соглашения в полном объеме, без каких-либо оговорок и исключений.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>3. <strong>ПРЕДМЕТ СОГЛАШЕНИЯ</strong></span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>3.1. Предметом настоящего Соглашения является предоставление Пользователю доступа к информации, и онлайн сервисам, представленным&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>в Личном кабинете</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>3.2.&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личный кабинет</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;предоставляет Пользователю следующие виды сервисов:</span></p>
    <ul class="decimal_type" style="text-align: left;color: black;margin-left: 25px">
        <li style="list-style: disc"><span
                style='font-family:"Times New Roman",serif;color:black;background:white;background:white;'>свободный доступ к информации с правом просмотра данной информации;</span></li>
        <li style="list-style: disc"><span
                style='font-family:"Times New Roman",serif;color:black;background:white;background:white;'>доступ к</span><span
                style='font-family:"Times New Roman",serif;background:white;'>&nbsp;информации содержащий отображение текущих долгов или переплат по своему договору аренды</span><span
                style='font-family:"Times New Roman",serif;color:black;background:white;'>;</span></li>
        <li style="list-style: disc"><span
                style='font-family:"Times New Roman",serif;color:black;background:white;background:white;'>предоставление Пользователю возможности запросов&nbsp;</span><span
                style="background:white;">справок по всем платежам, скачивания</span><span
                style='font-family:"Times New Roman",serif;background:white;'>&nbsp;</span><span
                style='font-family:"Times New Roman",serif;background:white;'>графиков платежей</span><span
                style='font-family:"Times New Roman",serif;color:black;background:white;'>;</span></li>
        <li style="list-style: disc"><span
                style='font-family:"Times New Roman",serif;color:black;background:white;background:white;'>Возможность обратной связи и составления обращений в адрес Общества.</span></li>
    </ul>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>3.3. Под действие настоящего Соглашения подпадают все существующие на данный момент сервисы&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личного кабинета</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>, а также любые их последующие модификации и появляющиеся в дальнейшем сервисы.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>3.4. Доступ к&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личному кабинету</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;предоставляется на безвозмездной основе.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>3.5. Настоящее Соглашение является публичной офертой. Получая доступ к&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личному кабинету</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>, Пользователь соглашается с условиями Соглашения и считается присоединившимся к настоящему Соглашению.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>3.6. Использование материалов и сервисов&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личного кабинета</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;регулируется нормами действующего законодательства&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Республики Казахстан.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4. <strong>ПРАВА И ОБЯЗАННОСТИ СТОРОН</strong></span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.1.&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Общество</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;вправе:</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.1.1. Изменять правила пользования&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личного кабинета</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>, а также изменять содержание Личного кабинета. Изменения вступают в силу с момента публикации новой редакции Соглашения&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>в</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личном кабинете.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.1.2. Ограничить доступ к Личному кабинету или&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>некоторым его функциональным возможностям</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;в случае нарушения Пользователем условий настоящего Соглашения.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.1.3. В целях пресечения или предотвращения нарушения Пользовательского соглашения и/или причинения ущерба Обществу (например, DDoS-атаки или иные хакерские атаки, неавторизованное использование программных средств), Общество вправе ограничивать доступ таких Пользователей и/или третьих лиц к https://skcn.kz/ru/cabinet путем блокирования доступа к https://skcn.kz/ru/cabinet соответствующего ip-адреса или диапазона ip-адресов.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.2. Пользователь вправе:</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.2.1. Получить доступ к использованию Личного кабинета в ознакомительных и подобных целях, а также к онлайн сервисам, представленным&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>в</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личном кабинете.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.2.2. Задавать любые вопросы, относящиеся к услугам, представленным&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>в</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личном кабинете и иной информации, размещенной&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>в</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личном кабинете, используя раздел Личного кабинета &laquo;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Мои Обращения</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&raquo;.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.2.3. Пользоваться&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личным кабинетом</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;исключительно в целях и порядке, предусмотренных Соглашением и не запрещенных законодательством&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Республики Казахстан</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.3. Пользователь Личного кабинета обязуется:</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.3.1. Соблюдать имущественные и неимущественные права авторов и иных правообладателей при использовании Личного кабинета.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.3.2. Не предпринимать действий, которые могут рассматриваться как нарушающие нормальную работу Личного кабинета.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.3.3. Не распространять с использованием Личного кабинета любую конфиденциальную и охраняемую законодательством&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Республики Казахстан</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;информацию о физических или юридических лицах.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.3.4. Избегать любых действий, в результате которых может быть нарушена конфиденциальность информации, охраняемой законодательством&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Республики Казахстан</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.3.5. Не использовать&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личный кабинет</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;для распространения информации рекламного характера.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.3.6. Не использовать сервисы Личного кабинета с целью:</span></p>
    <ul class="decimal_type" style="text-align: left;color: black;margin-left: 25px">
        <li style="list-style: disc"><span
                style='font-family:"Times New Roman",serif;color:black;background:white;background:white;'>Побуждения к совершению противоправных действий, а также содействия лицам, действия которых направлены на нарушение ограничений и запретов, действующих на территории&nbsp;</span><span
                style='font-family:"Times New Roman",serif;background:white;'>Республики Казахстан;</span></li>
        <li style="list-style: disc"><span
                style='font-family:"Times New Roman",serif;color:black;background:white;background:white;'>Нарушения прав несовершеннолетних лиц и (или) причинение им вреда в любой форме</span><span
                style='font-family:"Times New Roman",serif;background:white;background:white;'>;</span></li>
        <li style="list-style: disc"><span
                style='font-family:"Times New Roman",serif;color:black;background:white;background:white;'>Представления себя за другого человека или представителя организации и (или) сообщества без достаточных на то прав, в том числе за Администрацию Личного кабинета.</span></li>
        <li style="list-style: disc"><span
                style='font-family:"Times New Roman",serif;color:black;background:white;background:white;'>Введения в заблуждение относительно свойств и характеристик какой-либо услуги, размещенной на Личном кабинете.</span></li>
        <li style="list-style: disc"><span
                style='font-family:"Times New Roman",serif;color:black;background:white;background:white;'>Некорректного сравнения услуги, а также формирования негативного отношения к лицам, пользующимся/не пользующимися определенными услугами, или осуждения таких лиц.</span></li>
    </ul>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.3.7. Самостоятельно следить за сохранностью своих Учетных данных и не раскрывать их третьим лицам. Пользователь не вправе передавать свои Учетные данные третьим лицам, а также прямо или косвенно разрешать третьим лицам использовать его Учетные данные для авторизации в Личном кабинете.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.3.8. Пользователь обязан немедленно изменить Учетные данные, если у него либо у Общества есть причины. подозревать, что эти данные были раскрыты или могут быть использованы неуполномоченными им третьими лицами.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Исправить п.6.3 в Политике конфиденциальности и обработки персональных данных, в части skcn,kz, стоят запятые.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.4. Пользователю запрещается:</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.4.1. Нарушать надлежащее функционирование Личного кабинета.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.4.2. Любым способом обходить навигационную структуру Личного кабинета для получения или попытки получения любой информации, документов или материалов любыми средствами, которые специально не представлены сервисами Личного кабинета.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.4.3. Несанкционированный доступ к функциям Личного кабинета, любым другим системам или сетям, относящимся к данному Личному кабинету, а также к любым услугам, предлагаемым&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>в</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личном кабинете.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.4.4. Нарушать систему безопасности или аутентификации&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>в</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личном кабинете.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.4.5. Отслеживать или пытаться отслеживать любую информацию о любом другом Пользователе Личного кабинета.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4.4.6. Использовать&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личный кабинет</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;в любых целях, запрещенных законодательством&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Республики Казахстан</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>, а также подстрекать к любой незаконной деятельности или другой деятельности, нарушающей права АО &laquo;Samruk-Kazyna Construction&raquo; или других лиц.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>5. <strong>ИСПОЛЬЗОВАНИЕ ЛИЧНОГО КАБИНЕТА</strong></span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>5.1. Сайт не может быть скопирован, опубликован, воспроизведен, передан или распространен любым способом, полностью или частично, без предварительного письменного согласия АО &laquo;Samruk-Kazyna Construction&raquo;.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>5.2. Сайт защищен авторским правом, а также другими правами, связанными с интеллектуальной собственностью, и законодательством о недобросовестной конкуренции.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>5.</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>3</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>. Пользователь несет персональную ответственность за сохранение конфиденциальности информации, а также за всю без исключения деятельность, которая ведётся от имени Пользователя.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>5.</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>4</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>. Настоящее Соглашение распространяет свое действия на все дополнительные положения и условия по оказанию услуг, предоставляемых&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>в</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личном кабинете.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>5.</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>5</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>. Информация, размещаемая на Личном кабинете не должна истолковываться как изменение настоящего Соглашения.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>5.</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>6</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>. Администрация Личного кабинета имеет право в любое время без уведомления Пользователя вносить изменения в перечень услуг, предлагаемых&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>в</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личном кабинете</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>5.</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>7</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>. Документ &laquo;Политика конфиденциальности&raquo; регулирует в соответствующей части и распространяет свое действие на использование Пользователем Личного кабинета.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>6. ОТВЕТСТВЕННОСТЬ</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>6.</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>1</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>. АО &laquo;Samruk-Kazyna Construction&raquo; не несет ответственности за:</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>6.</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>1</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>.1. Задержки или сбои в процессе совершения операции, возникшие вследствие непреодолимой силы, а также любого случая неполадок в телекоммуникационных, компьютерных, электрических и иных смежных системах.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>6.</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>1</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>.2. Действия систем переводов, банков, платежных систем и за задержки связанные с их работой.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>6.</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>1</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>.3. Ненадлежащее функционирование Личного кабинета, в случае, если Пользователь не имеет необходимых технических средств для его использования, а также не несет никаких обязательств по обеспечению пользователей такими средствами.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>7. <strong>НАРУШЕНИЕ УСЛОВИЙ ПОЛЬЗОВАТЕЛЬСКОГО СОГЛАШЕНИЯ</strong></span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>7.1.&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Общество</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>вправе раскрыть любую собранную о Пользователе Личного кабинета информацию, если раскрытие необходимо в связи с расследованием или жалобой в отношении неправомерного использования Личного кабинета либо для установления (идентификации) Пользователя, который может нарушать или вмешиваться в права&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Общества</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;или в права других Пользователей Личного кабинета.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>7.2.&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Общество</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;имеет право раскрыть любую информацию о Пользователе, которую посчитает необходимой для выполнения положений действующего законодательства или судебных решений, обеспечения выполнения условий настоящего Соглашения, защиты прав Пользователей.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>7.3.&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Общество</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;имеет право раскрыть информацию о Пользователе, если действующее законодательство&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Республики Казахстан</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;требует или разрешает такое раскрытие.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>7.4.&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Общество</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;вправе без предварительного уведомления Пользователя прекратить доступ к Личному кабинету, если Пользователь нарушил настоящее Соглашение или содержащиеся в иных документах условия пользования&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личным кабинетом</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>, а также в случае прекращения действия Личного кабинета либо по причине технической неполадки.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>7.5.&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Общество</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;не несет ответственности перед Пользователем или третьими лицами за прекращение доступа к Личному кабинету в случае нарушения Пользователем любого положения настоящего Соглашения или иного документа, содержащего условия пользования&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личного кабинета</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>8. <strong>РАЗРЕШЕНИЕ СПОРОВ</strong></span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>8.1. В случае возникновения любых разногласий или споров между Сторонами Настоящего Соглашения обязательным условием до обращения в суд является предъявление претензии (письменного предложения о добровольном урегулировании спора).</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>8.2. Получатель претензии в течение 30 календарных дней со дня ее получения, письменно уведомляет заявителя претензии о результатах рассмотрения претензии.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>8.3. При невозможности разрешить спор в добровольном порядке любая из Сторон вправе обратиться в суд за защитой своих прав, которые предоставлены им действующим законодательством&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Республики Казахстан</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>8.4. При нарушении условий данного пункта любой иск или основания для иска погашаются исковой давностью.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>9. <strong>ДОПОЛНИТЕЛЬНЫЕ УСЛОВИЯ</strong></span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>9.1.&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Общество</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;не принимает предложения от Пользователя относительно изменений настоящего Пользовательского соглашения.</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;text-align:justify;line-height:normal;'><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>9.2. Отзывы и вопросы Пользователя, размещенные&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>в</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Личном кабинете, не являются конфиденциальной информацией и могут быть использованы&nbsp;</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>Обществом</span><span
            style='font-size:16px;font-family:"Times New Roman",serif;color:black;background:white;'>&nbsp;без ограничений.</span></p>


    </span>
    </div>

</div>
